routes/web.php
<?php

use App\Http\Controllers\ActivitiesController;
use App\Http\Controllers\ProjectsController;
use App\Http\Controllers\QuestionMapperController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\SurveysController;
use App\Http\Controllers\UsersController;

use App\Models\Question_mapper;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::post('questions/fetchActivity', [QuestionsController::class,'fetchActivity'])->name('questions.fetchActivity');
Route::post('users/fetchActivity', [UsersController::class,'fetchActivity'])->name('users.fetchActivity');
Route::post('question_mapper/fetchActivity', [QuestionMapperController::class,'fetchActivity'])->name('question_mapper.fetchActivity');



Route::group(['as'=>'admin.', 'prefix' => 'admin', 'namespace'=>'', ], function(){

       Route::resource('questions', QuestionsController::class);
       Route::post('questions.destroy_status/{id}', [QuestionsController::class,'destroy_status'])->name('questions.destroy_status');
       Route::resource('projects', ProjectsController::class);
       Route::post('projects.destroy_status/{id}', [ProjectsController::class,'destroy_status'])->name('projects.destroy_status');
       Route::resource('activities', ActivitiesController::class);
       Route::post('activities.destroy_status/{id}', [ActivitiesController::class,'destroy_status'])->name('activities.destroy_status');
       Route::resource('users', UsersController::class);
       Route::post('users.destroy_status/{id}', [UsersController::class,'destroy_status'])->name('users.destroy_status');
       Route::resource('question_mapper', QuestionMapperController::class);
       Route::post('question_mapper.destroy_status/{id}', [QuestionMapperController::class,'destroy_status'])->name('question_mapper.destroy_status');
       Route::resource('survey', SurveysController::class);
       Route::get('surveyfilter', [SurveysController::class,'filter'])->name('surveyfilter');

 });

app/Models/Projects.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Projects extends Model
{
    use HasFactory;
    // public function projects()
    // {
    //     // to display name insted  of id
    //     return $this->belongsTo(Projects::class, 'project_id', 'id');
    // }
    public function activities()
    {

        return $this->hasMany(Activity::class, 'activity_id', 'id');
    }
    public function questions()
    {

        return $this->hasMany(Questions::class, 'question_id', 'id');
    }

}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Services\ProjectsService;
use App\Models\Projects;
use Illuminate\Http\Request;

class ProjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public $service;
    public function __construct(){

       $this->service = new ProjectsService();
    }
    public function index()
    {
        $project = $this->service->all()->where('del_status' , 0);
        return view('projects.index', compact('project'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $project = Projects::All();
        return view('projects.create',compact('project'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $id = $request->input('id');

        if(empty($id)){

            $addprojects = $this->service->insert($request);
        }
        else{
            $addprojects = $this->service->update($request,$id);
        }

        return redirect()->route('admin.projects.index');
    }

    /**
     * Display the specified resource.
     */


    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $project =  Projects::find($id);

        return view('projects.edit',compact('project'));
    }

    /**
     * Update the specified resource in storage.
     */


    /**
     * Remove the specified resource from storage.
     */

     public function destroy_status($id)
    {
        $this->service->delete_status($id);
        return redirect()->route('admin.projects.index');
    }

}

resources/views/projects/create.blade.php
@extends('adminlte::page')
@section('content')
    <div class="c-container">

        <div class="p-div">
            <div class="p-left">

                <div class="">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Add Project</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->

                        <form action="{{ route('admin.projects.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf



                            <div class="card-body">
                                <div class="form-group">
                                    <label for="name">name</label>
                                    <input type="text" name="name" class="form-control" id="name"
                                        placeholder="">
                                </div>

                                <div class="col-sm-6">
                                        <!-- select -->

                                      </div>

                                    <!-- /.card-body -->

                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>


                        </form>
                    </div>
                    <!-- /.card -->

                @stop


                @section('js')
                    <!-- Bootstrap 4 -->
                    <script src="{{ url('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
                    <!-- bs-custom-file-input -->
                    {{-- <script src="{{ url('plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
                    <script>
                        $(document).ready(function() {
                            bsCustomFileInput.init()
                        })
                    </script> --}}
                @endsection

resources/views/projects/edit.blade.php
@extends('adminlte::page')
@section('content')
    <div class="c-container">

        <div class="p-div">
            <div class="p-left">


                <form action="{{ route('admin.projects.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" name="id" value="{{ $project->id }}" />


                    <div class="col-12">

                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Edit Project Name</h3>


                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="name">name</label>
                                    <input type="text" name="name" class="form-control" id="name"
                                        placeholder="" value="{{ $project->name }}">
                                </div>



                                    <!-- /.card-body -->

                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary">Update</button>
                                    </div>


                </form>

                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>







        </form>

    </div>




    </form>
@endsection
@section('js')
    <!-- Bootstrap 4 -->
    <script src="{{ url('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
@endsection

resources/views/projects/index.blade.php
{{-- @extends('layouts.app') --}}

@extends('adminlte::page')
@section('content')
    <div class="col-6">
        <a href="{{ route('admin.projects.create') }}"><button type="button" class="btn  btn-primary "
                style="width:150px;margin:5px;">Add Project</button></a>
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Project</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px; ">
                        <br />
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0" >
                <table class="table table-hover table-head-fixed  text-nowrap">
                    <thead>
                        <tr>
                            <th>S.N</th>
                            <th>name</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($project as $projects)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $projects->name }}</td>

                                <td >

                                    <form action="{{ route('admin.projects.destroy_status', [$projects->id]) }}"
                                        method="Post">
                                        @csrf
                                        <button type="submit" class="btn btn-danger"
                                            onclick="return confirm('Are you sure to delete?')">
                                            <i class="fa fa-lg fa-fw fa-trash"></i>
                                        </button>
                                        <a style="font-size:24px "class="btn btn-xs btn-default text-primary mx-1 shadow"
                                            title="Edit" href="{{ route('admin.projects.edit', [$projects->id]) }}">
                                            <i class="fa fa-lg fa-fw fa-pen"></i>
                                        </a>
                                    </form>


                                </td>

                            </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
@endsection
@extends('layouts.footer')