routes/web.php
<?php

use App\Http\Controllers\ActivitiesController;
use App\Http\Controllers\ProjectsController;
use App\Http\Controllers\QuestionMapperController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\SurveysController;
use App\Http\Controllers\UsersController;

use App\Models\Question_mapper;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::post('questions/fetchActivity', [QuestionsController::class,'fetchActivity'])->name('questions.fetchActivity');
Route::post('users/fetchActivity', [UsersController::class,'fetchActivity'])->name('users.fetchActivity');
Route::post('question_mapper/fetchActivity', [QuestionMapperController::class,'fetchActivity'])->name('question_mapper.fetchActivity');



Route::group(['as'=>'admin.', 'prefix' => 'admin', 'namespace'=>'', ], function(){

       Route::resource('questions', QuestionsController::class);
       Route::post('questions.destroy_status/{id}', [QuestionsController::class,'destroy_status'])->name('questions.destroy_status');
       Route::resource('projects', ProjectsController::class);
       Route::post('projects.destroy_status/{id}', [ProjectsController::class,'destroy_status'])->name('projects.destroy_status');
       Route::resource('activities', ActivitiesController::class);
       Route::post('activities.destroy_status/{id}', [ActivitiesController::class,'destroy_status'])->name('activities.destroy_status');
       Route::resource('users', UsersController::class);
       Route::post('users.destroy_status/{id}', [UsersController::class,'destroy_status'])->name('users.destroy_status');
       Route::resource('question_mapper', QuestionMapperController::class);
       Route::post('question_mapper.destroy_status/{id}', [QuestionMapperController::class,'destroy_status'])->name('question_mapper.destroy_status');
       Route::resource('survey', SurveysController::class);
       Route::get('surveyfilter', [SurveysController::class,'filter'])->name('surveyfilter');

 });

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function activities()
    {

        return $this->belongsTo(Activity::class, 'activity_id', 'id');
    }
    public function project()
    {
        // to display name insted  of id
        return $this->belongsTo(Projects::class, 'project_id', 'id');
    }
    public function district()
    {
        // to display name insted  of id
        return $this->belongsTo(Districts::class, 'district_id', 'id');
    }





}

app/Http/Controllers/Api/UsersController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Services\UsersService;
use App\Models\User;
use GrahamCampbell\ResultType\Success;
use Illuminate\Auth\Events\Login;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UsersController extends Controller
{
    public $service;
    public function __construct()
    {

        $this->service = new UsersService();
    }
    public function index()
    {
        $user = $this->service->all(['del_status' => '0', 'user_type' => 'BP']);
        return response()->json(['status'=>'success','msg'=>'','data'=> $user]);

    }
    public function login(Request $request){

        if(!Auth::attempt($request->only(['phone', 'password']))){
            return response()->json([
                'status' => 'false',
                'message' => 'phone & Password does not match with our record.',
            ]);
        }

        $user = User::where('phone', $request->phone)->first();
        $token=$user->createToken("API TOKEN")->plainTextToken;
        $user->save();


        return response()->json([
            'status' => 'success',
            'message' => 'User Logged In Successfully',
            'token' =>  $token,
            'user_id'=>$user->id,

        ], 200);
    }
    public function getProfile(Request $request,$id){
        $user= User::where('id',$id)->first();
    return response()->json(['status'=>'success','msg'=>'','data'=> ['user'=>$user, 'activity'=>$user->activities->name, 'project'=>$user->project->name]]);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Services\UsersService;
use App\Http\Services\ActivitiesService;
use App\Http\Services\ProjectsService;
use App\Http\Services\DistrictService;
use App\Models\Activity;
use App\Models\Projects;
use App\Models\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public $service;
    public $activity_service;
    public $project_service;
    public $district_service;

    public function __construct(){

       $this->service = new UsersService();
       $this->activity_service = new ActivitiesService();
       $this->project_service = new ProjectsService();
       $this->district_service = new DistrictService();
    }
    public function index()
    {
        $user = $this->service->all(['del_status'=>'0','user_type'=>'BP']);

        return view('users.index', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $activities = $this->activity_service->all();
        // $projects = $this->project_service->all();
        $data['projects']=Projects::get(['name','id']);

        $districts = $this->district_service->all();



        return view('users.create',$data,compact('activities','districts'));
    }
    public function fetchActivity(Request $request){
        $data['activity']= Activity::where('project_id',$request->project_id)->get(['name','id']);
        return response()->json($data);
    }
    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $id = $request->input('id');

        if(empty($id)){

            $addprojects = $this->service->insert($request);
        }
        else{
            $addprojects = $this->service->update($request,$id);
        }

        return redirect()->route('admin.users.index');
    }

    /**
     * Display the specified resource.
     */


    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $user =  User::find($id);
        $activities = $this->activity_service->all();
        $data['projects']=Projects::get(['name','id']);
        // $projects = $this->project_service->all();
        $districts = $this->district_service->all();

        return view('users.edit',$data,compact('user','activities','districts'));
    }

    /**
     * Update the specified resource in storage.
     */


    /**
     * Remove the specified resource from storage.
     */
    public function destroy_status($id)
    {
        $this->service->delete_status($id);
        return redirect()->route('admin.users.index');
    }

}

resources/views/Users/create.blade.php
@extends('adminlte::page')
@section('content')
    <div class="c-container">

        <div class="p-div">
            <div class="p-left">

                <div class="">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Add Users</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->

                        <form action="{{ route('admin.users.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf



                            <div class="card-body">
                                <div class="form-group">
                                    <label for="name">name</label>
                                    <input type="text" name="name" class="form-control" id="name" placeholder="">
                                </div>
                                <div class="form-group">
                                    <label for="phone">phone</label>
                                    <input type="text" name="phone" class="form-control" id="phone" placeholder="">
                                </div>
                                <div class="form-group">
                                    <label for="name">password</label>
                                    <input type="text" name="password" class="form-control" id="password"
                                        placeholder="">
                                </div>
                                <div class="form-group">
                                    <label for="name">country</label>
                                    <input type="text" name="country" class="form-control" id="country" placeholder="">
                                </div>


                                <div class="form-group">
                                    <label for="district_id">district_id</label>
                                    <select name="district_id" class="form-control" id="district_id">
                                        <option value="">--Select Project--</option>
                                        @foreach ($districts as $district)
                                            <option value="{{ $district->id }}">{{ $district->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                {{-- project --}}
                                <div class="form-group">
                                    <label for="project_id">project_id</label>
                                    <select name="project_id" class="form-control" id="project_id">
                                        <option value="">--Select Project--</option>
                                        @foreach ($projects as $project)
                                            <option value="{{ $project->id }}">{{ $project->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                {{-- Activity --}}
                                <div class="form-group">
                                    <label for="activity_id">activity_id</label>
                                    <select name="activity_id" class="form-control" id="activity_id">
                                    <option value=""> --Select Activity-- </option>
                                    </select>
                                </div>




                                <input type="hidden" name="user_type" value="BP" />


                                <div class="col-sm-6">
                                    <!-- select -->

                                </div>

                                <!-- /.card-body -->

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>


                        </form>
                    </div>
                    <!-- /.card -->

                @stop


                @section('js')
                    <!-- Bootstrap 4 -->
                    <script src="{{ url('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

                    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
                        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
                    <script type="text/javascript">
                        $(document).ready(function() {
                            $('#project_id').change(function(event) {
                                var idprojects = this.value;
                                //  alert(idprojects);
                                $('#activity_id').html('');

                                $.ajax({
                                    url: "{{ url('users/fetchActivity') }}",
                                    type: 'POST',
                                    dataType: 'json',
                                    data: {
                                        project_id: idprojects,
                                        _token: "{{ csrf_token() }}"
                                    },
                                    success: function(response) {
                                        console.log(response);
                                        $('#activity_id').html('<option value=""> --Select Activity-- </option>');
                                        $.each(response.activity, function(index, val) {
                                            $('#activity_id').append('<option value="' + val.id + '">'
                                                +val.name + ' </option>');

                                        })

                                    }
                                })
                            })
                        })
                    </script>
                @endsection

resources/views/Users/edit.blade.php
@extends('adminlte::page')
@section('content')
    <div class="c-container">

        <div class="p-div">
            <div class="p-left">


                <form action="{{ route('admin.users.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" name="id" value="{{ $user->id }}" />


                    <div class="col-12">

                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Edit Users</h3>


                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="name">name</label>
                                    <input type="text" name="name" class="form-control" id="name" placeholder=""
                                        value="{{ $user->name }}">
                                </div>
                                <div class="form-group">
                                    <label for="name">phone</label>
                                    <input type="text" name="phone" class="form-control" id="phone" placeholder=""
                                        value="{{ $user->phone }}">
                                </div>
                                <div class="form-group">
                                    <label for="password">password</label>
                                    <input type="text" name="password" class="form-control" id="password"
                                        placeholder="">
                                </div>
                                <div class="form-group">
                                    <label for="country">country</label>
                                    <input type="text" name="country" class="form-control" id="country" placeholder=""
                                        value="{{ $user->country }}">
                                </div>
                                <div class="form-group">
                                    <label for="district_id">district</label>
                                    <select name="district_id" class="form-control" id="district_id">
                                        <option value="">--Select Project--</option>
                                        @foreach ($districts as $district)
                                            <option
                                                value="{{ $district->id }}"@if ($district->id == $user->district_id) {{ 'selected =selected' }} @endif>
                                                {{ $district->name }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                                {{-- project --}}
                                <div class="form-group">
                                    <label for="project_id">project name</label>
                                    <select name="project_id" class="form-control" id="project_id">
                                        <option value="">--Select Project--</option>
                                        @foreach ($projects as $project)
                                            <option value="{{ $project->id }}"
                                                @if ($project->id == $user->project_id) {{ 'selected =selected' }} @endif>
                                                {{ $project->name }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                                {{-- Activity --}}
                                <div class="form-group">
                                    <label for="activity_id">activity_id</label>
                                    <select name="activity_id" class="form-control" id="activity_id">
                                        <option value=""> --Select Activity-- </option>
                                    </select>
                                </div>








                                <!-- /.card-body -->

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Update</button>
                                </div>


                </form>

                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>







        </form>

    </div>




    </form>
@endsection
@section('js')
    <!-- Bootstrap 4 -->
    <script src="{{ url('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#project_id').change(function(event) {
                var idprojects = this.value;
                //  alert(idprojects);
                $('#activity_id').html('');

                $.ajax({
                    url: "{{ url('users/fetchActivity') }}",
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        project_id: idprojects,
                        _token: "{{ csrf_token() }}"
                    },
                    success: function(response) {
                        console.log(response);
                        $('#activity_id').html(
                            '<option value=""> --Select Activity-- </option>');
                        $.each(response.activity, function(index, val) {
                            $('#activity_id').append('<option value="' + val.id + '">' +
                                val.name + ' </option>');

                        })

                    }
                })
            })
        })
    </script>
@endsection

resources/views/Users/index.blade.php
{{-- @extends('layouts.app') --}}

@extends('adminlte::page')
@section('content')
    <div class="col-12">
        <a href="{{ route('admin.users.create') }}"><button type="button" class="btn  btn-primary "
                style="width:150px;margin:5px;">Add user</button></a>
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">User</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px; ">
                        <br />
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0" style="height: 700px;">
                <table class="table table-hover table-head-fixed  text-nowrap">
                    <thead>
                        <tr>
                            <th>S.N</th>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>Country</th>
                            <th>District</th>
                            <th>Project Name</th>
                            <th>Activity</th>
                            <th>Action</th>


                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($user as $users)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $users->name }}</td>
                                <td>{{ $users->phone }}</td>

                                <td>{{ $users->country }}</td>
                                <td>{{ $users->district->name }}</td>
                                {{-- <td>{{ $users->district_id }}</td> --}}
                                <td>{{ $users->project->name }}</td>
                                <td>{{ $users->activities->name }}</td>







                                <td >
                                    <form action="{{ route('admin.users.destroy_status', [$users->id]) }}"
                                        method="Post">
                                        @csrf
                                        <button type="submit" style="font-size:16px" class="btn btn-danger"
                                            onclick="return confirm('Are you sure to delete?')">
                                            <i class="fa fa-lg fa-fw fa-trash"></i>
                                        </button>

                                        <a style="font-size:24px "class="btn btn-xs btn-default text-primary mx-1 shadow"
                                        title="Edit" href="{{ route('admin.users.edit', [$users->id]) }}">
                                        <i class="fa fa-lg fa-fw fa-pen"></i>
                                    </a>
                                </form>

                                </td>

                            </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
@endsection
@extends('layouts.footer')