routes/web.php
<?php

use App\Http\Controllers\ActivitiesController;
use App\Http\Controllers\ProjectsController;
use App\Http\Controllers\QuestionMapperController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\SurveysController;
use App\Http\Controllers\UsersController;

use App\Models\Question_mapper;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::post('questions/fetchActivity', [QuestionsController::class,'fetchActivity'])->name('questions.fetchActivity');
Route::post('users/fetchActivity', [UsersController::class,'fetchActivity'])->name('users.fetchActivity');
Route::post('question_mapper/fetchActivity', [QuestionMapperController::class,'fetchActivity'])->name('question_mapper.fetchActivity');



Route::group(['as'=>'admin.', 'prefix' => 'admin', 'namespace'=>'', ], function(){

       Route::resource('questions', QuestionsController::class);
       Route::post('questions.destroy_status/{id}', [QuestionsController::class,'destroy_status'])->name('questions.destroy_status');
       Route::resource('projects', ProjectsController::class);
       Route::post('projects.destroy_status/{id}', [ProjectsController::class,'destroy_status'])->name('projects.destroy_status');
       Route::resource('activities', ActivitiesController::class);
       Route::post('activities.destroy_status/{id}', [ActivitiesController::class,'destroy_status'])->name('activities.destroy_status');
       Route::resource('users', UsersController::class);
       Route::post('users.destroy_status/{id}', [UsersController::class,'destroy_status'])->name('users.destroy_status');
       Route::resource('question_mapper', QuestionMapperController::class);
       Route::post('question_mapper.destroy_status/{id}', [QuestionMapperController::class,'destroy_status'])->name('question_mapper.destroy_status');
       Route::resource('survey', SurveysController::class);
       Route::get('surveyfilter', [SurveysController::class,'filter'])->name('surveyfilter');

 });

app/Models/Questions.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Questions extends Model
{
    use HasFactory;

    // public function question()
    // {
    //     // to display name insted  of id
    //     return $this->belongsTo(Questions::class, 'question_id', 'id');
    // }
    public function activities()
    {

        return $this->belongsTo(Activity::class, 'activity_id', 'id');
    }
    public function project()
    {
        // to display name insted  of id
        return $this->belongsTo(Projects::class, 'project_id', 'id');
    }
    public function user()
    {
        // to display name insted  of id
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
    public function questionmappers()
    {
        // to display name insted  of id
        return $this->hasMany(QuestionMapper::class, 'question_id', 'id');
    }
}

app/Http/Controllers/Api/QuestionController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Services\QuestionsService;


class QuestionController extends Controller
{
    public $service;
    public function __construct()
    {

        $this->service = new QuestionsService();
    }
    public function index($id)
    {

        $question = $this->service->forntendquestion($id);
        return response()->json(['status'=>'success','msg'=>'','data'=> $question]);

    }
}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Services\ActivitiesService;
use App\Http\Services\ProjectsService;
use App\Http\Services\QuestionsService;
use App\Models\Activity;
use App\Models\Projects;
use App\Models\Questions;
use Illuminate\Http\Request;

class QuestionsController extends Controller
{
    private $answer_columns = [];
    /**
     * Display a listing of the resource.
     */
    public $service;
    public $activity_service;
    public $project_service;



    public function __construct(){

       $this->service = new QuestionsService();
       $this->activity_service = new ActivitiesService();
       $this->project_service = new ProjectsService();


       for($i=1;$i<=100;$i++){
        $this->answer_columns[] = 'A'.$i;
    }



    }
    public function index()
    {
        // $question = $this->service->all();
        $question = $this->service->all()->where('del_status' , 0);
        return view('questions.index', compact('question'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $activities = $this->activity_service->all();
        // $projects = $this->project_service->all();
        $data['projects']=Projects::get(['name','id']);

        $used_answer_columns = Questions::pluck('answer_column')->toArray();
		$free_answer_columns = array_filter($this->answer_columns, function($item) use($used_answer_columns){ return !in_array($item, $used_answer_columns); });

        return view('questions.create',$data,compact('activities', 'free_answer_columns'));
    }
    public function fetchActivity(Request $request){
        $data['activity']= Activity::where('project_id',$request->project_id)->get(['name','id']);
        return response()->json($data);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $id = $request->input('id');

        if(empty($id)){

            $addquestions = $this->service->insert($request);
        }
        else{
            $addquestions = $this->service->update($request,$id);
        }

        return redirect()->route('admin.questions.index');
    }


    /**
     * Display the specified resource.
     */


    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $question =  Questions::find($id);
        $activities = $this->activity_service->all();
        // $projects = $this->project_service->all();
        $data['projects']=Projects::get(['name','id']);
        return view('questions.edit',$data, compact('question','activities'));
    }

    /**
     * Update the specified resource in storage.
     */


    /**
     * Remove the specified resource from storage.
     */
    // public function delete(Request $request, $id){
    //     $questions = Questions::where('id', $id)->first();
    //     $questions->del_status = 1;
    //     $questions->save();
    //     return redirect()->route('admin.questions.index', ['id'=>$request->input('return_url_id')]);


    //  }
    public function destroy_status($id)
    {
        $this->service->delete_status($id);
        return redirect()->route('admin.questions.index');
    }
}

resources/views/questions/create.blade.php
@extends('adminlte::page')
@section('content')
    <div class="c-container">

        <div class="p-div">
            <div class="p-left">

                <div class="">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Add Question</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->

                        <form action="{{ route('admin.questions.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf



                            <div class="card-body">
                                {{-- project --}}
                                <div class="form-group">
                                    <label for="question">question</label>
                                    <input type="text" name="question" class="form-control" id="question"
                                        placeholder="">
                                </div>
                                <div class="form-group">
                                    <label for="slug">slug</label>
                                    <input type="text" name="slug" class="form-control" id="slug" placeholder="">
                                </div>
                                <div class="form-group">
                                    <label>Question Type</label>
                                    <select name="type" class="form-control select-role-id" id="question_type">
                                        <option value="">Select</option>
                                        <option value="textfield">TextField</option>
                                        <option value="textarea">TextArea</option>
                                        <option value="selectbox">Selectbox</option>
                                        <option value="checkbox">Checkbox</option>
                                        <option value="radio">Radio Button</option>
                                        <option value="date">Date</option>
                                        <option value="fileupload">File Upload</option>
                                    </select>
                                </div>


                                <div class="qc_option d-none">
                                    <label for="option">option</label>
                                    <textarea name="option" class="form-control" rows="3"
                                        placeholder="option1:value1|option2:value2|option3:value3......" style="height: 64px;" id="option"></textarea>
                                </div>



                                <div class="form-group">
                                    <label for="class_name">class_name</label>
                                    <input type="text" name="class_name" class="form-control" id="class_name"
                                        placeholder="">
                                </div>
                                <div class="form-group">
                                    <label for="answer_column">answer_column</label>
                                    <input type="text" name="answer_column" class="form-control" id="answer_column"
                                        placeholder="" value="{{ array_shift($free_answer_columns) }}" readonly>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputFile">photos</label>
                                    <div class="input-group">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" name="image"
                                                id="exampleInputFile">
                                            <label class="custom-file-label" for="exampleInputFile">Choose image</label>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="status">status</label>
                                        <div class="form-group">
                                            <select class="form-control" name="status">
                                                <option value="1">Active</option>
                                                <option value="0">InActive</option>
                                            </select>
                                        </div>

                                    </div>
                                    <div class="col-sm-6">
                                        <!-- select -->

                                    </div>

                                    <!-- /.card-body -->

                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>


                        </form>
                    </div>
                    <!-- /.card -->

                @stop


                @section('js')
                    <!-- Bootstrap 4 -->
                    <script src="{{ url('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
                    <!-- bs-custom-file-input -->
                    <script src="{{ url('plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
                    <script>
                        $(document).ready(function() {
                            bsCustomFileInput.init()
                            $('#question_type').on('change', function(e) {
                                console.log($(this).val());
                                if (($(this).val() == "selectbox") || ($(this).val() == "checkbox") || ($(this).val() ==
                                        "radio")) {
                                    $('.qc_option').removeClass('d-none');
                                } else {
                                    $('.qc_option').addClass('d-none');

                                }

                            });




                        })
                    </script>
                    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
                        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
                    <script></script>
                @endsection

resources/views/questions/edit.blade.php
@extends('adminlte::page')
@section('content')
    <div class="c-container">

        <div class="p-div">
            <div class="p-left">


                <form action="{{ route('admin.questions.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" name="id" value="{{ $question->id }}" />


                    <div class="col-12">

                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Edit question Form</h3>


                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">

                                <div class="card-body">
                                    {{-- project --}}
                                    <div class="form-group">
                                        <label for="question">question</label>
                                        <input type="text" name="question" class="form-control" id="question"
                                            placeholder="" value="{{ $question->question }}">
                                    </div>
                                    <div class="form-group">
                                        <label for="slug">slug</label>
                                        <input type="text" name="slug" class="form-control" id="slug"
                                            placeholder="" value="{{ $question->slug }}">
                                    </div>
                                    <div class="form-group">
                                        <label>Question Type</label>
                                        <select name="type" class="form-control select-role-id" id="question_type">
                                            <option value="">Select</option>
                                            <option value="textfield"
                                                @if ('textfield' == $question->type) {{ 'selected =selected' }} @endif>
                                                TextField</option>
                                            <option value="textarea"
                                                @if ('textarea' == $question->type) {{ 'selected =selected' }} @endif>TextArea
                                            </option>
                                            <option value="selectbox"
                                                @if ('selectbox' == $question->type) {{ 'selected =selected' }} @endif>
                                                Selectbox</option>
                                            <option value="checkbox"
                                                @if ('checkbox' == $question->type) {{ 'selected =selected' }} @endif>Checkbox
                                            </option>
                                            <option value="radio"
                                                @if ('radio' == $question->type) {{ 'selected =selected' }} @endif>Radio
                                                Button</option>
                                            <option value="date"
                                                @if ('date' == $question->type) {{ 'selected =selected' }} @endif>Date
                                            </option>
                                            <option value="fileupload"
                                                @if ('fileupload' == $question->type) {{ 'selected =selected' }} @endif>File
                                                Upload</option>
                                        </select>
                                    </div>
                                    <div class="q_option d-none">
                                        <label for="option">option</label>
                                        <textarea name="option" class="form-control" rows="3"
                                            placeholder="option1:value1|option2:value2|option3:value3......" style="height: 64px;" id="option">{{ $question->option }}</textarea>
                                    </div>


                                    <div class="form-group">
                                        <label for="class_name">class_name</label>
                                        <input type="text" name="class_name" class="form-control" id="class_name"
                                            placeholder="" value="{{ $question->class_name }}">
                                    </div>
                                    <div class="form-group">
                                        <label for="answer_column">answer_column</label>
                                        <input type="text" name="answer_column" class="form-control" id="answer_column"
                                            placeholder="" value="{{ $question->answer_column }}" readonly>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputFile">photos</label>
                                        <div class="input-group">
                                            <div class="custom-file">
                                                <input type="file" class="custom-file-input" name="image"
                                                    id="exampleInputFile">
                                                <label class="custom-file-label" for="exampleInputFile">Choose image</label>
                                            </div>
                                            <img src="{{ url('images/' . $question->image) }}"
                                                style=" padding-left:5px;height:100px;width:100px"alt="photo">
                                        </div>

                                        <div class="form-group">
                                            <label for="status">status</label>
                                            <div class="form-group">
                                                <select class="form-control" name="status">
                                                    <option value="1">Active</option>
                                                    <option value="0">InActive</option>
                                                </select>
                                            </div>

                                        </div>
                                        <div class="col-sm-6">
                                            <!-- select -->

                                        </div>

                                        <!-- /.card-body -->

                                        <div class="card-footer">
                                            <button type="submit" class="btn btn-primary">Update</button>
                                        </div>
                </form>
                    <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>







        </form>

    </div>




    </form>
@endsection
@section('js')
    <!-- Bootstrap 4 -->
    <script src="{{ url('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <!-- bs-custom-file-input -->
    <script src="{{ url('plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            bsCustomFileInput.init()
        })
    </script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#question_type').on('change', function(e) {
                console.log($(this).val());
                if (($(this).val() == "selectbox") || ($(this).val() == "checkbox") || ($(this).val() == "radio")) {
                    $('.q_option').removeClass('d-none');
                } else {
                    $('.q_option').addClass('d-none');

                }

            });


            let q_type = $('#question_type').val();
            if(q_type == 'checkbox' || q_type == 'selectbox' || q_type == 'radio'){
                $('.q_option').removeClass('d-none');
            }
        })
    </script>
@endsection

resources/views/questions/index.blade.php
{{-- @extends('layouts.app') --}}

@extends('adminlte::page')
@section('content')
    <div class="col-12">
        <a href="{{ route('admin.questions.create') }}"><button type="button" class="btn  btn-primary "
                style="width:150px;margin:5px;">Add Question</button></a>
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Questions</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px; ">
                        <br />
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0" style="height: 700px;">
                <table class="table table-hover table-head-fixed  text-nowrap">
                    <thead>
                        <tr>
                            <th>S.N</th>
                            <th>question</th>
                            <th>slug</th>
                            <th>type</th>
                            <th>option</th>
                            <th>class_name</th>
                            <th>answer_column</th>
                            <th>image</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($question as $questions)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $questions->question }} </td>
                                <td>{{ $questions->slug }}</td>
                                <td>{{ $questions->type }}</td>
                                <td>{{ $questions->option }}</td>
                                <td>{{$questions->class_name}}</td>
                                <td>{{ $questions->answer_column}}</td>

                                <td><img src="{{ url('images/' . $questions->image) }}" style="height:60px;width:60px"
                                        alt="photo"></td>
                                <td> {{ $questions->status }}</td>
                                <td>
                                    {{-- <form action="{{ route('admin.questions.destroy_status', [$questions->id]) }}"
                                        method="Post">
                                        @csrf --}}
                                        {{-- <button type="submit" style="font-size:16px" class="btn btn-danger"
                                            onclick="return confirm('Are you sure to delete?')">
                                            <i class="fa fa-lg fa-fw fa-trash"></i>
                                        </button> --}}

                                        <a style="font-size:24px "class="btn btn-xs btn-default text-primary mx-1 shadow"
                                        title="Edit" href="{{ route('admin.questions.edit', [$questions->id]) }}">
                                        <i class="fa fa-lg fa-fw fa-pen"></i>
                                    </a>
                                {{-- </form> --}}

                                </td>

                            </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
@endsection
@extends('layouts.footer')