routes/web.php
<?php

use App\Http\Controllers\ActivitiesController;
use App\Http\Controllers\ProjectsController;
use App\Http\Controllers\QuestionMapperController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\SurveysController;
use App\Http\Controllers\UsersController;

use App\Models\Question_mapper;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::post('questions/fetchActivity', [QuestionsController::class,'fetchActivity'])->name('questions.fetchActivity');
Route::post('users/fetchActivity', [UsersController::class,'fetchActivity'])->name('users.fetchActivity');
Route::post('question_mapper/fetchActivity', [QuestionMapperController::class,'fetchActivity'])->name('question_mapper.fetchActivity');



Route::group(['as'=>'admin.', 'prefix' => 'admin', 'namespace'=>'', ], function(){

       Route::resource('questions', QuestionsController::class);
       Route::post('questions.destroy_status/{id}', [QuestionsController::class,'destroy_status'])->name('questions.destroy_status');
       Route::resource('projects', ProjectsController::class);
       Route::post('projects.destroy_status/{id}', [ProjectsController::class,'destroy_status'])->name('projects.destroy_status');
       Route::resource('activities', ActivitiesController::class);
       Route::post('activities.destroy_status/{id}', [ActivitiesController::class,'destroy_status'])->name('activities.destroy_status');
       Route::resource('users', UsersController::class);
       Route::post('users.destroy_status/{id}', [UsersController::class,'destroy_status'])->name('users.destroy_status');
       Route::resource('question_mapper', QuestionMapperController::class);
       Route::post('question_mapper.destroy_status/{id}', [QuestionMapperController::class,'destroy_status'])->name('question_mapper.destroy_status');
       Route::resource('survey', SurveysController::class);
       Route::get('surveyfilter', [SurveysController::class,'filter'])->name('surveyfilter');

 });

app/Models/Activity.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Activity extends Model
{
    use HasFactory;
    public function projects()
    {
        // to display name insted  of id
        return $this->belongsTo(Projects::class, 'project_id', 'id');
    }
        public function questionmappers()
        {
            // to display name insted  of id
            return $this->hasMany(QuestionMapper::class, 'question_id', 'id');
        }

}

app/Http/Controllers/ActivitiesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Services\ActivitiesService;
use App\Http\Services\ProjectsService;
use App\Models\Activity;
use Illuminate\Http\Request;

class ActivitiesController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public $service;
    public $project_service;
    public function __construct(){

       $this->service = new ActivitiesService();
       $this->project_service = new ProjectsService();
    }
    public function index()
    {
        $activity = $this->service->all(['del_status'=>'0']);

        return view('activities.index', compact('activity'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $projects = $this->project_service->all();
        return view('activities.create',compact('projects'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $id = $request->input('id');

        if(empty($id)){

            $addprojects = $this->service->insert($request);
        }
        else{
            $addprojects = $this->service->update($request,$id);
        }

        return redirect()->route('admin.activities.index');
    }

    /**
     * Display the specified resource.
     */


    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $activity =  Activity::find($id);
        $projects = $this->project_service->all();

        return view('activities.edit',compact('activity','projects'));
    }

    /**
     * Update the specified resource in storage.
     */


    /**
     * Remove the specified resource from storage.
     */
    public function destroy_status($id)
    {
        $this->service->delete_status($id);
        return redirect()->route('admin.activities.index');
    }

}

resources/views/activities/create.blade.php
@extends('adminlte::page')
@section('content')
    <div class="c-container">

        <div class="p-div">
            <div class="p-left">

                <div class="">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Add Activities</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->

                        <form action="{{ route('admin.activities.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf



                            <div class="card-body">
                                <div class="form-group">
                                    <label for="name">name</label>
                                    <input type="text" name="name" class="form-control" id="name"
                                        placeholder="">
                                </div>
                                <div class="form-group">
                                    <label for="project_id">project_id</label>
                                    <select name="project_id" class="form-control" id="project_id">
                                        <option value="">--Select Project--</option>
                                        @foreach ($projects as $project)
                                            <option value="{{ $project->id }}">{{ $project->name }}</option>
                                        @endforeach
                                    </select>
                                </div>


                                <div class="col-sm-6">
                                        <!-- select -->

                                      </div>

                                    <!-- /.card-body -->

                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>


                        </form>
                    </div>
                    <!-- /.card -->

                @stop


                @section('js')
                    <!-- Bootstrap 4 -->
                    <script src="{{ url('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
                    <!-- bs-custom-file-input -->
                    {{-- <script src="{{ url('plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
                    <script>
                        $(document).ready(function() {
                            bsCustomFileInput.init()
                        })
                    </script> --}}
                @endsection

resources/views/activities/edit.blade.php
@extends('adminlte::page')
@section('content')
    <div class="c-container">

        <div class="p-div">
            <div class="p-left">


                <form action="{{ route('admin.activities.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" name="id" value="{{ $activity->id }}" />


                    <div class="col-12">

                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Edit Activitie</h3>


                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="name">name</label>
                                    <input type="text" name="name" class="form-control" id="name"
                                        placeholder="" value="{{ $activity->name }}">
                                </div>
                                <div class="form-group">
                                    <label for="project_id">Project Name</label>
                                    <select name="project_id" class="form-control" id="project_id">
                                        <option value="">--Select Project--</option>
                                        @foreach ($projects as $project)
                                            <option value="{{ $project->id }}"  @if ($project->id ==$activity->project_id) {{'selected =selected'}}
                                                @endif>{{ $project->name }}</option>
                                        @endforeach
                                    </select>
                                </div>



                                    <!-- /.card-body -->

                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary">Update</button>
                                    </div>


                </form>

                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>







        </form>

    </div>




    </form>
@endsection
@section('js')
    <!-- Bootstrap 4 -->
    <script src="{{ url('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
@endsection

resources/views/activities/index.blade.php
{{-- @extends('layouts.app') --}}

@extends('adminlte::page')
@section('content')
    <div class="col-12">
        <a href="{{ route('admin.activities.create') }}"><button type="button" class="btn  btn-primary "
                style="width:150px;margin:5px;">Add Activities</button></a>
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Activities</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px; ">
                        <br />
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0" style="height: 700px;">
                <table class="table table-hover table-head-fixed  text-nowrap">
                    <thead>
                        <tr>
                            <th>S.N</th>
                            <th>name</th>
                            <th>Project Name</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($activity as $activities)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $activities->name }}</td>
                                <td>{{ $activities->projects->name }}</td>



                                <td>
                                    <form action="{{ route('admin.activities.destroy_status', [$activities->id]) }}"
                                        method="Post">
                                        @csrf
                                        <button type="submit" class="btn btn-danger"
                                            onclick="return confirm('Are you sure to delete?')">
                                            <i class="fa fa-lg fa-fw fa-trash"></i>
                                        </button>

                                        <a style="font-size:24px "class="btn btn-xs btn-default text-primary mx-1 shadow"
                                        title="Edit" href="{{ route('admin.activities.edit', [$activities->id]) }}">
                                        <i class="fa fa-lg fa-fw fa-pen"></i>
                                    </a>
                                </form>

                                </td>

                            </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
@endsection
@extends('layouts.footer')